drop table if exists stu_exams;

create table stu_exams(id bigint generated by default as identity primary key, firstName varchar(255), lastName varchar(255), subject varchar(255), result bigint, grade varchar(255));